version: "3.9"
services:
  archives_app:
    build:
      context: .
      args:
        USERNAME: adankert
        USER_UID: 1000
    user: "${USERNAME}"
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: |
      sh -c "
      service redis-server start
      flask run --host=0.0.0.0"
    volumes:
      - R:/:/app/Data/PPC_Records
      - V:/:/app/Data/Archive_Data
      - Z:/:/app/Data/Cannon_Scans
      - C:/:/app/Data/PC
    privileged: true
  redis:
    image: "redis:alpine"
