version: "3.9"
services:
  archives_app:
    build: .
    restart: unless-stopped

    depends_on:
      - redis
    volumes:
      - .:/app/archives_app
    ports:
      - "127.0.0.1:5000:5000"
    command: |
      sh -c "
      mount -t cifs -o "username=adankert,password=1156DAVpass,domain=ppcou,vers=1.0" //ppdo-fs05.ppcou.ucsc.edu/Archive_Data /app/Data/Archive_Data
      mount -t cifs -o "username=adankert,password=1156DAVpass,domain=ppcou,vers=1.0" //PPDO-ACT-RECORD.ppcou.ucsc.edu/PPC_Records /app/Data/PPC_Records
      mount -t cifs -o "username=adankert,password=1156DAVpass,domain=ppcou,vers=1.0" //ppdo-fs05.ppcou.ucsc.edu/Cannon_Scans /app/Data/Cannon_Scans
      flask run --host=0.0.0.0 --port=5000 --reload"
    privileged: true
  redis:
    image: "redis:alpine"
