version: "3.9"
services:
  archives_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: |
      sh -c "
      service redis-server start
      mount -t cifs -o "username=adankert,password=1156DAVpass,domain=ppcou,vers=1.0" //ppdo-fs05.ppcou.ucsc.edu/Archive_Data /app/Data/Archive_Data
      mount -t cifs -o "username=adankert,password=1156DAVpass,domain=ppcou,vers=1.0" //PPDO-ACT-RECORD.ppcou.ucsc.edu/PPC_Records /app/Data/PPC_Records
      mount -t cifs -o "username=adankert,password=1156DAVpass,domain=ppcou,vers=1.0" //ppdo-fs05.ppcou.ucsc.edu/Cannon_Scans /app/Data/Cannon_Scans
      flask run --host=0.0.0.0"
    privileged: true
  redis:
    image: "redis:alpine"
